projekt_inzynierski/medical_clinic/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from .views import ReceptionHomePage, PatientSearchMedic, Visits, PatientDetail
from .views import PatientSearchReception, VisitSearch, AddPatient, ShowPatient, AddVisit, EditPatient, EditVisit, DeleteVisit
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('medic/patient_search', PatientSearchMedic.as_view(), name='patient_search'),
    path('medic/visits', Visits.as_view(), name='medic_visits'),
    path('<int:pk>/medic/patient_history', PatientDetail.as_view(), name='patient_history'),
    path('recepcja/home', ReceptionHomePage.as_view(), name='reception_home'),
    path('<int:pk>/recepcja/patient/show', ShowPatient.as_view(), name='reception_patient_show'),
    path('recepcja/patient/search', PatientSearchReception.as_view(), name='reception_patient_search'),
    path('recepcja/visit/search', VisitSearch.as_view(), name='reception_visit_search'),
    path('recepcja/patient/add', AddPatient.as_view(), name='reception_patient_add'),
    path('<int:pk>/recepcja/visit/add', AddVisit.as_view(), name='reception_visit_add'),
    path('<int:pk>/recepcja/patient/edit', EditPatient.as_view(), name='reception_patient_edit'),
    path('<int:pk>/recepcja/visit/edit', EditVisit.as_view(), name='reception_visit_edit'),
    path('<int:pk>/recepcja/visit/delete', DeleteVisit.as_view(), name='reception_visit_delete'),
]

projekt_inzynierski/projekt_inzynierski/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('medical_clinic/admin/', admin.site.urls),
    path('medical_clinic/', include('medical_clinic.urls')),
]

projekt_inzynierski/medical_clinic/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    class Meta:
        permissions = [
            ("is_administration", "Administration"),
            ("is_doctor", "Doctor"),
            ("is_reception", "Receptionist"),
        ]

class Patient(models.Model):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    pesel = models.CharField(max_length=20, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    sex = models.CharField(max_length=20, blank=True)
    birth_date= models.DateField()


class PatientHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    entry = models.TextField(max_length=5000, blank=True)
    medicine = models.CharField(max_length=500, blank=True)
    dose = models.CharField(max_length=500, blank=True)


class Visit(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date_time = models.DateTimeField()

projekt_inzynierski/medical_clinic/forms.py
from django import forms
from django.forms import ModelForm
from .models import Patient, Visit
from django.contrib.auth.models import User


class PatientHistoryForm(forms.Form):
    entry = forms.CharField(required=True)
    medicine = forms.CharField(required=True)
    dose = forms.CharField(required=True)

class PatientSearchForm(forms.Form):
    pesel = forms.CharField(required=True)

class VisitSearchForm(forms.Form):
    pesel = forms.CharField(required=False)
    date = forms.DateField(required=False)

class VisitEditForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ('patient', 'doctor', 'date_time')

class VisitAddForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ('patient', 'doctor', 'date_time')

projekt_inzynierski/medical_clinic/views/medical_views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.edit import DeleteView, FormView
from django.http import HttpResponse
from ..models import Visit, PatientHistory, Patient
from datetime import date
from ..forms import PatientHistoryForm, PatientSearchForm

    
class Visits(PermissionRequiredMixin, ListView):
    permission_required = 'medical_clinic.is_doctor'
    template_name = "medical_clinic/list_visits.html"
    context_object_name = 'visits'

    def get_queryset(self):
        active_user = self.request.user.pk
        queryset = Visit.objects.filter(doctor__pk=active_user).filter(date_time__date=date.today())
        return queryset

class PatientDetail(PermissionRequiredMixin, FormView, DetailView):
    permission_required = 'medical_clinic.is_doctor'
    form_class = PatientHistoryForm
    template_name = "medical_clinic/patient_history.html"
    success_url = "patient_history"
    model = Patient

    def form_valid(self, form):
        form_data = form.cleaned_data
        discount = PatientHistory(
            patient=Patient.objects.get(pk=self.kwargs['pk']),
            entry=form_data['entry'],
            medicine=form_data['medicine'],
            dose=form_data['dose'],
        )
        discount.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PatientDetail, self).get_context_data(**kwargs)
        context['history'] = PatientHistory.objects.filter(patient__pk=self.kwargs['pk'])
        context['patient_info'] = Patient.objects.filter(pk=self.kwargs['pk'])[0]
        context['aa'] = 'tttr'
        return context

class PatientSearchMedic(PermissionRequiredMixin, ListView):
    permission_required = 'medical_clinic.is_doctor'
    model = Patient
    form_class = PatientSearchForm
    context_object_name = 'patients'
    template_name = 'medical_clinic/list_patients.html'
    patients = []


    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            return Patient.objects.filter(pesel=form.cleaned_data['pesel'])
        return Patient.objects.all()

projekt_inzynierski/medical_clinic/views/receptionist_views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView 
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.edit import DeleteView, FormView
from django.http import HttpResponse
from django.urls import reverse
from ..models import Visit, Patient
from ..forms import PatientSearchForm, VisitSearchForm, VisitAddForm, VisitEditForm
from django.contrib.auth.models import User

class ReceptionHomePage(PermissionRequiredMixin, TemplateView):
    permission_required = 'medical_clinic.is_reception'
    template_name = "medical_clinic/recepcja_home.html"

class AddPatient(PermissionRequiredMixin, CreateView):
    permission_required = 'medical_clinic.is_reception'
    model = Patient
    fields = '__all__'
    template_name = 'medical_clinic/reception_add_patient.html'

    def get_success_url(self):
        return reverse('reception_patient_show',args=(self.object.pk,))

class AddVisit(PermissionRequiredMixin, CreateView):
    permission_required = 'medical_clinic.is_reception'
    model = Visit
    form_class = VisitAddForm
    template_name = 'medical_clinic/reception_add_visit.html'

    def get_context_data(self, **kwargs):
        context = super(AddVisit, self).get_context_data(**kwargs)
        context['doctors'] = User.objects.filter(groups__name='doctors')
        context['patient'] = Patient.objects.filter(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('reception_patient_show',args=(self.object.patient.pk,))

class PatientSearchReception(PermissionRequiredMixin, ListView):
    permission_required = 'medical_clinic.is_reception'
    model = Patient
    form_class = PatientSearchForm
    context_object_name = 'patients'
    template_name = 'medical_clinic/reception_search_patient.html'
    patients = []

    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            return Patient.objects.filter(pesel=form.cleaned_data['pesel'])
        return Patient.objects.all()

class VisitSearch(PermissionRequiredMixin, ListView):
    permission_required = 'medical_clinic.is_reception'
    model = Visit
    form_class = VisitSearchForm
    context_object_name = 'visits'
    template_name = 'medical_clinic/reception_search_visit.html'
    visits = []

    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            form = form.cleaned_data
            print(form)
            if form['pesel'] and form['date']:
                return Visit.objects.filter(date_time__date=form['date']).filter(patient__pesel=form['pesel'])
            elif form['date']:
                return Visit.objects.filter(date_time__date=form['date'])
            elif form['pesel']:
                return Visit.objects.filter(patient__pesel=form['pesel'])
        return Visit.objects.all()

class EditPatient(PermissionRequiredMixin, UpdateView ):
    permission_required = 'medical_clinic.is_reception'
    model = Patient
    fields = '__all__'
    template_name = 'medical_clinic/reception_edit_patient.html'

    def get_success_url(self):
        return reverse('reception_patient_show',args=(self.object.pk,))

class EditVisit(PermissionRequiredMixin, UpdateView ):
    permission_required = 'medical_clinic.is_reception'
    model = Visit
    template_name = 'medical_clinic/reception_edit_visit.html'
    form_class = VisitEditForm
    visits = []

    def get_success_url(self):
        print(self.object.patient.pk)
        return reverse('reception_patient_show',args=(self.object.patient.pk,))

class DeleteVisit(PermissionRequiredMixin, DeleteView ):
    permission_required = 'medical_clinic.is_reception'
    model = Visit

    def get_success_url(self):
        return reverse('reception_patient_show',args=(self.object.patient.pk,))

class ShowPatient(PermissionRequiredMixin, DetailView):
    permission_required = 'medical_clinic.is_reception'
    template_name = "medical_clinic/reception_show_patient.html"
    model = Patient

    def get_context_data(self, **kwargs):
        context = super(ShowPatient, self).get_context_data(**kwargs)
        context['visits'] = Visit.objects.filter(patient__pk=self.kwargs['pk'])
        context['patient_info'] = Patient.objects.filter(pk=self.kwargs['pk'])[0]
        context['aa'] = 'tttr'
        return context

projekt_inzynierski/medical_clinic/templates/medical_clinic/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block head %}
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  {% block style %}
  {% endblock %}
</head>

<body>
  <header>
    <div class="container text-center text-black pt-5 pb-5">
        <h1 id="logo">
            Przychodnia lekarska
        </h1>
    </div>
  </header>
    
    {% block nav %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

projekt_inzynierski/medical_clinic/templates/medical_clinic/base_reception.html
{% extends "./base.html" %}
{% load static %}
{% block head %}
  <title>Przychodnia lekarska - recepcja</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'medical_clinic/reception_page.css' %}">
{% endblock %}

{% block nav %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'reception_home' %}">Główna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reception_patient_search' %}">Pacjenci</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reception_visit_search' %}">Wizyty</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reception_patient_add' %}">Dodaj pacjenta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Wyloguj</a>
        </li>
      </ul>
     </div>
    </div>
  </nav>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/doctor_base.html
{% extends "./base.html" %}
{% load static %}
{% block head %}
  <title>Przychodnia lekarska - lekarz</title>
{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'medical_clinic/doctor_page.css' %}">
{% endblock %}

{% block nav %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'medic_visits' %}">Wizyty</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'patient_search' %}">Pacjenci</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Wyloguj</a>
        </li>
      </ul>
     </div>
    </div>
  </nav>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/indexx.html
aaaa

projekt_inzynierski/medical_clinic/templates/medical_clinic/list_patients.html
{% extends "./doctor_base.html" %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="PESEL" name="pesel">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success" type="submit">Szukaj</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </br></br>

    <div class="d-flex">
    <ul class="list-group mx-auto justify-content-center">
        <li class="list-group-item mb-3" style="width: 100%;">Lista pacjentów</li>
        {% for patient in patients %}
        <li class="list-group-item mb-3" style="width: 100%;">
            <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="font-weight: normal;">Imię i nazwisko: {{ patient.first_name }} {{ patient.last_name }}</th>
                    <td>PESEL: {{ patient.pesel }}</td>
                    <td><a href="{% url 'patient_history' patient.pk %}"><button type="button" class="btn btn-primary">Wybierz</button></a></td>
                  </tr>
                </tbody>
            </table>
        </li>
        {% endfor %}
    </ul>
    </div>


   
</div>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/list_visits.html
{% extends "./doctor_base.html" %}


{% block content %}

<div class="container">
</br></br>

<div class="d-flex">
    <ul class="list-group mx-auto justify-content-center">
        <li class="list-group-item mb-3" style="width: 100%;">Lista dzisiejszych wizyt</li>
        {% for visit in visits %}
        <li class="list-group-item mb-3" style="width: 100%;">
            <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="font-weight: normal;">Imię i nazwisko: {{ visit.patient.first_name }} {{ visit.patient.last_name }}</th>
                    <td>PESEL: {{ visit.patient.pesel }}</td>
                    <td>Godzina: {{ visit.date_time }}</td>
                    <td><a href="{% url 'patient_history' visit.patient.pk %}"><button type="button" class="btn btn-primary">Wybierz</button></a></td>
                  </tr>
                </tbody>
            </table>
        </li>
        {% endfor %}
    </ul>
</div>


</div>



{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/patient_history.html
{% extends "./doctor_base.html" %}


{% block content %}

<div class="container">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
          Informacje o pacjencie
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Imię: {{ patient_info.first_name }}</li>
          <li class="list-group-item">Nazwisko: {{ patient_info.last_name }}</li>
          <li class="list-group-item">Pesel: {{ patient_info.pesel }}</li>
          <li class="list-group-item">Numer telefonu: {{ patient_info.phone_number }}</li>
          <li class="list-group-item">Płeć: {{ patient_info.sex }}</li>
          <li class="list-group-item">Data urodzenia: {{ patient_info.birth_date }}</li>
        </ul>
      </div>
    </br></br>
    <div class="overflow-auto p-3 mb-3 mb-md-0 mr-md-3 bg-light" style="max-width: 100%; max-height: 500px;">
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Opis</th>
                <th scope="col">Lekarstwa</th>
                <th scope="col">Dawkowanie</th>
              </tr>
            </thead>
            <tbody>
                {% for his in history %}
                <tr>
                    <td style="font-weight: normal;">{{ his.entry }}</td>
                    <td>{{ his.medicine }}</td>
                    <td>{{ his.dose }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
    </br>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="entry">Opis</label>
          <textarea class="form-control" id="entry" name="entry" rows="3"></textarea>
        </div>
        <div class="form-group">
          <label for="medicine">Lekarstwa</label>
          <textarea class="form-control" id="medicine" name="medicine" rows="2"></textarea>
        </div>
        <div class="form-group">
            <label for="dose">Dawkowanie</label>
            <textarea class="form-control" id="dose" name="dose" rows="2"></textarea>
        </div>
        </br>
        <div class="form-group">
            <input type="submit" name="submit" class="btn btn-info btn-md" value="Dodaj">
        </div>
      </form>
   
</div>



{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/recepcja_home.html
{% extends "./base_reception.html" %}


{% block content %}
<div class="container">

  Tekst powitalny

</div>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/reception_add_visit.html
{% extends "./base_reception.html" %}


{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" id="id_patient" name="patient" value="{{ patient.first.pk }}">

        <div class="form-group row">
            <label for="doctor" class="col-sm-2 col-form-label">Lekarz</label>

            <div class="col-sm-8">
                <select class="form-control" id="doctor" name="doctor">
                    {% for doctor in doctors %}
                    <option value="{{ doctor.pk }}">{{ doctor.first_name }} {{ doctor.last_name }} {{ doctor.username }}</option>
                    {% endfor %}
                </select>
            </div>
          </div>
        <br>
        <div class="form-group row">
            <label for="date_time" class="col-sm-2 col-form-label">Data i czas</label>
            <div class="col-sm-8">
              <input type="datetime-local" class="form-control" id="formGroupExampleInput" id="date_time" name="date_time">
            </div>
        </div>
        <br>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Dodaj">
        </div>
    
    </form>
</div>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/reception_edit_patient.html
{% extends "./base_reception.html" %}


{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="first_name" class="col-sm-2 col-form-label">Imię</label>
            <div class="col-sm-8">
                {{ form.first_name }}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="last_name" class="col-sm-2 col-form-label">Nazwisko</label>
            <div class="col-sm-8">
                {{ form.last_name }}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="pesel" class="col-sm-2 col-form-label">Pesel</label>
            <div class="col-sm-8">
                {{ form.pesel }}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="phone_number" class="col-sm-2 col-form-label">Numer telefonu</label>
            <div class="col-sm-8">
                {{ form.phone_number }}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="sex" class="col-sm-2 col-form-label">Płeć</label>
            <div class="col-sm-8">
                {{ form.sex }}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="birth_date" class="col-sm-2 col-form-label">Data urodzenia</label>
            <div class="col-sm-8">
                {{ form.birth_date }}
            </div>
        </div>
        <br>
        <button type="submit", class="btn btn-primary">SUBMIT</button>
    </form>
</div>
{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/reception_edit_visit.html
{% extends "./base_reception.html" %}


{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Edytuj</button>
    </form>
</div>

{% endblock %}

projekt_inzynierski/medical_clinic/templates/medical_clinic/reception_search_patient.html
{% extends "./base_reception.html" %}


{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="PESEL" name="pesel">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </br></br>

    <div class="d-flex">
    <ul class="list-group mx-auto justify-content-center">
        <li class="list-group-item mb-3" style="width: 100%;">Lista pacjentów</li>
        {% for patient in patients %}
        <li class="list-group-item mb-3" style="width: 100%;">
            <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="font-weight: normal;">Imię i nazwisko: {{ patient.first_name }} {{ patient.last_name }}</th>
                    <td>PESEL: {{ patient.pesel }}</td>
                    <td><a href="{% url 'reception_patient_show' patient.pk %}"><button type="button" class="btn btn-primary">Wybierz</button></a></td>
                  </tr>
                </tbody>
            </table>
        </li>
        {% endfor %}
    </ul>
    </div>
</div>

{% endblock %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="PESEL" name="pesel">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success" type="submit">Szukaj</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </br></br>

    <div class="d-flex">
    <ul class="list-group mx-auto justify-content-center">
        <li class="list-group-item mb-3" style="width: 100%;">Lista pacjentów</li>
        {% for patient in patients %}
        <li class="list-group-item mb-3" style="width: 100%;">
            <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="font-weight: normal;">Imię i nazwisko: {{ patient.first_name }} {{ patient.last_name }}</th>
                    <td>PESEL: {{ patient.pesel }}</td>
                    <td><a href="{% url 'reception_patient_show' patient.pk %}"><button type="button" class="btn btn-primary">Wybierz</button></a></td>
                  </tr>
                </tbody>
            </table>
        </li>
        {% endfor %}
    </ul>
    </div>
</div>

projekt_inzynierski/medical_clinic/templates/medical_clinic/reception_search_visit.html
{% extends "./base_reception.html" %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="PESEL" name="pesel">
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="date" name="date">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </br></br>
    
    <div class="d-flex">
    <ul class="list-group mx-auto justify-content-center">
        <li class="list-group-item mb-3" style="width: 100%;">Lista wizyt</li>
        {% for visit in visits %}
        <li class="list-group-item mb-3" style="width: 100%;">
            <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="font-weight: normal;">Imię i nazwisko: {{ visit.patient.first_name }} {{ visit.patient.last_name }}</th>
                    <td>PESEL: {{ visit.patient.pesel }}</td>
                    <td>Lekarz: {{ visit.doctor.first_name }} {{ visit.doctor.last_name }}</td>
                    <td>Date i czas: {{ visit.date_time }}</td>
                    <td><a href="{% url 'reception_visit_edit' visit.pk %}"><button type="button" class="btn btn-primary">Edytuj</button></a></td>
                    <td>
                        <form action="{% url 'reception_visit_delete' visit.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Usuń">
                        </form>
                    </td>
                  </tr>
                </tbody>
            </table>
        </li>
        {% endfor %}
    </ul>
    </div>
    
</div>


{% endblock %}